### ISSUE TITLE
v1.8.0 breaks the test to check the command line output.

### ISSUE THREAD

**Issue by Milly** [vim-denops/deno-denops-test#24]
#16 (included in [v1.8.0](https://github.com/vim-denops/deno-denops-test/releases/tag/v1.8.0)) breaks the test to check the command line output.

v1.8.0 set `verbose=1`, which breaks tests that expect `verbose=0`.

It must be written as a specification or modified.

**Comment by lambdalisue** [comment]
Plugins usually should work independent from the value of `verbose` so I don't think we should revert that change. Documentation should be enough so it won't block #23.

fyi. I noticed denops-std has bug on that, thanks to that change 👍 
https://github.com/vim-denops/deno-denops-std/pull/244

**Comment by Milly** [comment]
Okay, I agree that developers writing tests should be careful.
